apiVersion: apps/v1
kind: Deployment
metadata:
  name: matriculacion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matriculacion-service
  template:
    metadata:
      labels:
        app: matriculacion-service
    spec:
      containers:
        - name: matriculacion-service
          image: emherrerat/matriculacion-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: DB_URL
              value: "jdbc:postgresql://postgres-service:5432/matriculacion_db"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              value: "admin123"
            - name: MATERIA_SERVICE_URL
              value: "http://materia-service:8082"
            - name: COMPROBANTE_SERVICE_URL
              value: "http://comprobante-service:8084"
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: matriculacion-service
spec:
  type: LoadBalancer
  selector:
    app: matriculacion-service
  ports:
    - port: 8083
      targetPort: 8083